[package]
name = "fasty"
version = "0.1.5"
edition = "2021"

[lib]
name = "fasty"
path = "src/lib.rs"

[[bin]]
name = "fasty"
path = "src/main.rs"
required-features = []

[dependencies]
winit = "0.30"
wgpu = { version = "22", features = ["wgsl"] }
alacritty_terminal = "0.24"
portable-pty = "0.8"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.3"
log = "0.4"
env_logger = "0.11"
freetype-rs = { version = "0.37", features = ["bundled"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
parking_lot = "0.12"
raw-window-handle = "0.6"
unicode-width = "0.1"
rustix = { version = "0.38", features = ["std"] }
image = "0.25"
arboard = { version = "3", features = ["wayland-data-control"] }
resvg = "0.47.0"
usvg = "0.47.0"
tiny-skia = "0.12.0"

[build-dependencies]
winres = "0.1"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(all(target_os = "linux", not(windows)))'.dependencies]
x11 = { version = "2.21", features = ["xlib", "xfixes"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
