//! Terminal state wrapper using alacritty_terminal.

use std::io::Write;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::thread;

use alacritty_terminal::term::test::TermSize;
use alacritty_terminal::term::Config as AlacrittyConfig;
use alacritty_terminal::vte::ansi::{Processor, StdSyncHandler};
use parking_lot::Mutex as ParkingMutex;
use portable_pty::{native_pty_system, CommandBuilder, MasterPty, PtySize};

use crate::config::FontConfig;
use crate::event_listener::EventListenerProxy;

#[derive(Debug, Clone)]
pub enum AppEvent {
    Wakeup,
    Exit,
    ForceExit,
    ConfigChanged,
    Bell,
    ClipboardStore(String),
    ClipboardLoad(u8),
    CwdChanged(std::path::PathBuf),
    TitleChanged(String),
    CommandStarted,
    CommandFinished { duration_ms: u128, exit_code: Option<i32> },
}



pub struct TerminalState {
    term: Arc<ParkingMutex<alacritty_terminal::term::Term<EventListenerProxy>>>,
    render_generation: Arc<AtomicU64>,
    writer: Arc<ParkingMutex<Box<dyn Write + Send>>>,
    master: Arc<ParkingMutex<Box<dyn MasterPty + Send>>>,
    shell_pid: Option<u32>,
}

impl TerminalState {
    pub fn new(
        executable: &str,
        exec_args: &[String],
        cwd: Option<&str>,
        scrollback: usize,
        _font_config: FontConfig,
        cell_width: f32,
        cell_height: f32,
        viewport_width: f32,
        viewport_height: f32,
        proxy: winit::event_loop::EventLoopProxy<AppEvent>,
    ) -> anyhow::Result<Self> {
        let cell_w = (cell_width as usize).max(1);
        let cell_h = (cell_height as usize).max(1);
        let cols = ((viewport_width as usize) / cell_w).max(80);
        let rows = ((viewport_height as usize) / cell_h).max(24);

        let mut config = AlacrittyConfig::default();
        config.scrolling_history = scrollback.min(3000);
        let size = TermSize::new(cols, rows);

        let pty_system = native_pty_system();
        let pair = pty_system
            .openpty(PtySize {
                rows: rows as u16,
                cols: cols as u16,
                pixel_width: (cols as u16) * (cell_width as u16),
                pixel_height: (rows as u16) * (cell_height as u16),
            })
            .expect("Failed to open PTY");

        let mut cmd = CommandBuilder::new(executable);
        cmd.env("TERM", "xterm-256color");
        cmd.env("COLORTERM", "truecolor");
        cmd.env("TERM_PROGRAM", "fasty");
        if let Some(dir) = cwd {
            cmd.cwd(dir);
        }
        if let Ok(lang) = std::env::var("LANG") {
            cmd.env("LANG", lang);
        }
        if let Ok(path) = std::env::var("PATH") {
            cmd.env("PATH", path);
        }

        // Shell integration: write OSC 133 command markers so fasty can
        // detect command start/finish for duration tracking.
        let integration_path = std::env::temp_dir().join("fasty_shell_integration.sh");
        let integration_path_fish = std::env::temp_dir().join("fasty_shell_integration.fish");

        // POSIX shell integration (bash/zsh)
        let _ = std::fs::write(
            &integration_path,
            "# fasty shell integration — OSC 133 command markers\n\
             __fasty_cmd_start() {\n\
             \techo -ne \"\\e]133;B\\e\\\\\"\n\
             }\n\
             __fasty_prompt() {\n\
             \techo -ne \"\\e]133;D;$?\\e\\\\\"\n\
             \techo -ne \"\\e]133;A\\e\\\\\"\n\
             }\n\
             PROMPT_COMMAND=\"__fasty_prompt${PROMPT_COMMAND:+;$PROMPT_COMMAND}\"\n\
             trap '__fasty_cmd_start' DEBUG\n",
        );

        // Fish shell integration
        let _ = std::fs::write(
            &integration_path_fish,
            "# fasty shell integration — OSC 133 command markers\n\
             function __fasty_cmd_start --on-event fish_preexec\n\
             \techo -ne \"\\e]133;B\\e\\\\\"\n\
             end\n\
             function __fasty_cmd_end --on-event fish_postexec\n\
             \techo -ne \"\\e]133;D;$status\\e\\\\\"\n\
             end\n\
             function __fasty_prompt --on-event fish_prompt\n\
             \techo -ne \"\\e]133;A\\e\\\\\"\n\
             end\n",
        );

        // Wrap the shell command to source the integration before launching.
        let shell_name = std::path::Path::new(&executable)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("");

        if shell_name == "bash" && exec_args.is_empty() {
            // Bash: create wrapper bashrc that sources integration + user's .bashrc
            let user_bashrc = std::env::var("HOME")
                .map(|h| format!("{}/.bashrc", h))
                .unwrap_or_default();
            let wrapper_path = std::env::temp_dir().join("fasty_bashrc");
            let _ = std::fs::write(
                &wrapper_path,
                format!(
                    "# Auto-generated by fasty — shell integration wrapper\n\
                     . {}\n\
                     [ -f {} ] && . {}\n",
                    integration_path.display(),
                    user_bashrc,
                    user_bashrc,
                ),
            );
            cmd.args(&["--rcfile", wrapper_path.to_str().unwrap_or("")]);
        } else if shell_name == "zsh" && exec_args.is_empty() {
            // Zsh: use ZDOTDIR to inject .zshenv
            let zdotdir = std::env::temp_dir().join("fasty_zsh");
            let _ = std::fs::create_dir_all(&zdotdir);
            let _ = std::fs::write(
                zdotdir.join(".zshenv"),
                format!(". {}\n", integration_path.display()),
            );
            cmd.env("ZDOTDIR", zdotdir);
        } else if shell_name == "fish" && exec_args.is_empty() {
            // Fish: use -C to source integration on startup
            let source_cmd = format!("source {}", integration_path_fish.display());
            cmd.args(&["-C", &source_cmd]);
        } else {
            cmd.args(exec_args);
        }

        let child = pair.slave.spawn_command(cmd)?;
        let shell_pid = child.process_id();

        drop(pair.slave);

        let master: Box<dyn MasterPty + Send> = pair.master;
        let master_arc: Arc<ParkingMutex<Box<dyn MasterPty + Send>>> =
            Arc::new(ParkingMutex::new(master));
        let mut reader = master_arc
            .lock()
            .try_clone_reader()
            .expect("Failed to clone reader");
        let writer = master_arc.lock().take_writer().expect("Failed to take writer");

        let writer_boxed: Box<dyn Write + Send> = Box::new(writer);
        let writer_arc: Arc<ParkingMutex<Box<dyn Write + Send>>> =
            Arc::new(ParkingMutex::new(writer_boxed));

        let mut event_listener = EventListenerProxy::from_arc(writer_arc.clone());
        event_listener.set_app_proxy(proxy.clone());
        let term = Arc::new(ParkingMutex::new(alacritty_terminal::term::Term::new(
            config,
            &size,
            event_listener,
        )));

        // Write echo command directly in main thread (already done above)
        // Remove duplicate write in thread

        let render_generation = Arc::new(AtomicU64::new(0));
        let render_gen_clone = Arc::clone(&render_generation);
        let term_clone = Arc::clone(&term);
        let proxy_clone = proxy.clone();
        thread::spawn(move || {
            use std::io::Read;

            let mut buf = [0u8; 8192];
            let mut parser: Processor<StdSyncHandler> = Processor::new();

            // Generalized OSC pre-filter.
            // Detects OSC sequences (ESC ] <code> ; <payload> BEL/ST) and
            // dispatches events. Also filters them from the alacritty parser.
            //
            // Supported OSC codes:
            //   7   → CwdChanged (file:// URL)
            //   133 → CommandStarted / CommandFinished (FinalTerm markers)
            let mut osc_buf: Vec<u8> = Vec::new();
            let mut osc_active = false;
            let mut last_esc = false;

            // Command timing state
            let mut cmd_start_time: Option<std::time::Instant> = None;

            loop {
                match reader.read(&mut buf) {
                    Ok(0) => {
                        let _ = proxy_clone.send_event(AppEvent::Exit);
                        break;
                    }
                    Ok(n) => {
                        // Pass 1: Pre-scan bytes to detect and classify OSC sequences.
                        // We record which byte ranges to filter from the alacritty parser.
                        // Each range is (start_idx, end_idx) within buf[..n].
                        let mut filter_ranges: Vec<(usize, usize)> = Vec::new();
                        let mut osc_start_idx: usize = 0;

                        for (i, &byte) in buf[..n].iter().enumerate() {
                            if !osc_active {
                                if last_esc && byte == b']' {
                                    osc_active = true;
                                    osc_buf.clear();
                                    osc_start_idx = i - 1; // ESC was at i-1
                                    last_esc = false;
                                } else {
                                    last_esc = byte == 0x1b;
                                }
                            } else {
                                let dominated = if byte == 0x07 {
                                    true
                                } else if osc_buf.last() == Some(&0x1b) && byte == b'\\' {
                                    true
                                } else if osc_buf.len() > 4096 {
                                    true // safety abort
                                } else {
                                    false
                                };

                                if dominated {
                                    let osc_end = if byte == 0x07 {
                                        i + 1 // include BEL
                                    } else if byte == b'\\' {
                                        i + 1 // include backslash
                                    } else {
                                        i // safety: don't include this byte
                                    };

                                    filter_ranges.push((osc_start_idx, osc_end));

                                    // Classify and dispatch
                                    if byte != 0x1b || byte == b'\\' {
                                        // For ST terminator (ESC \), strip trailing ESC from buf
                                        let dispatch_buf = if byte == b'\\' && osc_buf.last() == Some(&0x1b) {
                                            &osc_buf[..osc_buf.len() - 1]
                                        } else {
                                            &osc_buf[..]
                                        };
                                        dispatch_osc(dispatch_buf, &proxy_clone, &mut cmd_start_time);
                                    }

                                    osc_active = false;
                                    osc_buf.clear();
                                } else {
                                    osc_buf.push(byte);
                                }
                            }
                        }

                        // Pass 2: Feed non-filtered bytes to alacritty parser.
                        let mut term_locked = term_clone.lock();
                        let mut filter_idx = 0;
                        for (i, &byte) in buf[..n].iter().enumerate() {
                            // Skip filtered ranges
                            if filter_idx < filter_ranges.len() {
                                let (start, end) = filter_ranges[filter_idx];
                                if i < end {
                                    if i >= start {
                                        continue;
                                    }
                                } else {
                                    filter_idx += 1;
                                }
                            }

                            parser.advance(&mut *term_locked, byte);
                        }
                        drop(term_locked);

                        render_gen_clone.fetch_add(1, Ordering::Relaxed);
                        let _ = proxy_clone.send_event(AppEvent::Wakeup);
                    }
                    Err(ref e) if e.kind() == std::io::ErrorKind::Interrupted => {
                        continue;
                    }
                    Err(_) => {
                        let _ = proxy_clone.send_event(AppEvent::Exit);
                        break;
                    }
                }
            }
        });

        Ok(Self {
            term,
            render_generation,
            writer: writer_arc,
            master: master_arc,
            shell_pid,
        })
    }

    pub fn shell_pid(&self) -> Option<u32> {
        self.shell_pid
    }

    pub fn write_to_pty(&self, bytes: &[u8]) {
        let mut w = self.writer.lock();
        let _ = w.write_all(bytes);
        let _ = w.flush();
    }

    pub fn mark_dirty(&self) {
        self.render_generation.fetch_add(1, Ordering::Relaxed);
    }

    pub fn update_scrollback(&self, scrollback: usize) {
        let mut term = self.term.lock();
        term.grid_mut().update_history(scrollback.min(3000));
    }

    pub fn resize(&mut self, cols: usize, rows: usize) {
        if cols == 0 || rows == 0 {
            return;
        }
        let mut term = self.term.lock();
        let size = TermSize::new(cols, rows);
        term.resize(size);
        drop(term);

        self.master.lock().resize(PtySize {
            rows: rows as u16,
            cols: cols as u16,
            pixel_width: 0,
            pixel_height: 0,
        }).ok();

        self.render_generation.fetch_add(1, Ordering::Relaxed);
    }

    pub fn scroll(&self, delta: isize) {
        let mut term = self.term.lock();
        use alacritty_terminal::grid::Scroll;
        term.scroll_display(Scroll::Delta(delta as i32));
    }

    pub fn display_offset(&self) -> usize {
        let term = self.term.lock();
        term.grid().display_offset()
    }

    pub fn history_size(&self) -> usize {
        use alacritty_terminal::grid::Dimensions;
        let term = self.term.lock();
        term.history_size()
    }

    pub fn update_render_generation(&self, rg: &Arc<AtomicU64>) {
        let current = self.render_generation.load(Ordering::Relaxed);
        rg.store(current, Ordering::Relaxed);
    }

    pub fn term(&self) -> &Arc<ParkingMutex<alacritty_terminal::term::Term<EventListenerProxy>>> {
        &self.term
    }
}

/// Strip the OSC 7 prefix (`7;`) from a raw OSC payload, returning the remainder.
/// Returns None if the payload does not start with `7;`.
fn strip_osc7_prefix(buf: &[u8]) -> Option<&[u8]> {
    if buf.len() >= 2 && buf[0] == b'7' && buf[1] == b';' {
        Some(&buf[2..])
    } else {
        None
    }
}

/// Decode a `file://` URL to a local filesystem path.
/// Accepts both `file:///abs/path` and `file://hostname/abs/path` forms.
fn file_url_to_path(buf: &[u8]) -> Option<std::path::PathBuf> {
    let s = std::str::from_utf8(buf).ok()?;
    let path = s.strip_prefix("file://")?;
    // Reject host-qualified URLs like `file://localhost/abs`
    let path = if let Some(slash_idx) = path.find('/') {
        let prefix = &path[..slash_idx];
        // If the "host" part contains a dot, colon, or looks like a real hostname, reject it
        if prefix.contains('.') || prefix.contains(':') || (!prefix.is_empty() && prefix != "localhost") {
            return None;
        }
        &path[slash_idx..]
    } else {
        path
    };
    // URL-decode minimal: %20 -> space, etc.
    let decoded = percent_decode(path);
    Some(std::path::PathBuf::from(decoded))
}

/// Minimal percent-decode for file:// paths.
fn percent_decode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let (Some(h), Some(l)) = (hex_digit(bytes[i + 1]), hex_digit(bytes[i + 2])) {
                if let Some(c) = char::from_u32((h as u32) * 16 + (l as u32)) {
                    out.push(c);
                    i += 3;
                    continue;
                }
            }
        }
        out.push(bytes[i] as char);
        i += 1;
    }
    out
}

fn hex_digit(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

/// Classify an OSC payload and emit the appropriate AppEvent.
/// `buf` contains the raw bytes between `ESC ]` and the terminator (BEL/ST),
/// i.e. the full `code;payload` string.
fn dispatch_osc(
    buf: &[u8],
    proxy: &winit::event_loop::EventLoopProxy<AppEvent>,
    cmd_start_time: &mut Option<std::time::Instant>,
) {
    // Split into code and payload at the first semicolon
    let semicolon = match buf.iter().position(|&b| b == b';') {
        Some(pos) => pos,
        None => return, // no payload separator
    };
    let code = &buf[..semicolon];
    let payload = &buf[semicolon + 1..];

    match code {
        b"7" => {
            // OSC 7: CwdChanged
            if let Some(path) = file_url_to_path(payload) {
                let _ = proxy.send_event(AppEvent::CwdChanged(path));
            }
        }
        b"133" => {
            tracing::info!("OSC 133 marker: payload={}", std::str::from_utf8(payload).unwrap_or("?"));
            // OSC 133: FinalTerm / VS Code command markers
            // A = prompt start, B = command start, C = command exec, D = command done
            match payload {
                b"B" => {
                    *cmd_start_time = Some(std::time::Instant::now());
                    tracing::info!("OSC 133: CommandStarted");
                    let _ = proxy.send_event(AppEvent::CommandStarted);
                }
                b"D" => {
                    // payload is just "D" — exit code was not included in this form
                    if let Some(start) = cmd_start_time.take() {
                        let duration_ms = start.elapsed().as_millis();
                        tracing::info!("OSC 133: CommandFinished duration={}ms", duration_ms);
                        let _ = proxy.send_event(AppEvent::CommandFinished {
                            duration_ms,
                            exit_code: None,
                        });
                    }
                }
                _ => {
                    // Could be "D;exitcode" — check for that
                    if payload.starts_with(b"D;") {
                        let exit_str = std::str::from_utf8(&payload[2..]).unwrap_or("0");
                        let exit_code: Option<i32> = exit_str.parse().ok();
                        if let Some(start) = cmd_start_time.take() {
                            let duration_ms = start.elapsed().as_millis();
                            tracing::info!("OSC 133: CommandFinished duration={}ms exit={:?}", duration_ms, exit_code);
                            let _ = proxy.send_event(AppEvent::CommandFinished {
                                duration_ms,
                                exit_code,
                            });
                        }
                    }
                    // A and C are ignored (no event needed)
                }
            }
        }
        _ => {}
    }
}